<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Sobre',
    'Because the application is in development mode, the email is not sent but saved as a file under.' => 'Como a aplicação está em modo de desenvolvimento, o email não é enviado, mas é salvo como um arquivo em.',
    'Body' => 'Corpo',
    'Captcha Code' => 'Código Captcha',
    'Contact' => 'Contato',
    'Contact us' => 'Contate-nos',
    'Email' => 'Email',
    'English' => 'Inglês',
    'Enter Body Here' => 'Digite o corpo aqui',
    'Enter Captcha Code Here' => 'Digite o código Captcha aqui',
    'Enter Email Here' => 'Digite o email aqui',
    'Enter Subject Here' => 'Digite o assunto aqui',
    'Enter Username Here' => 'Digite o nome de usuário aqui',
    'French' => 'Francês',
    'If you think this is a problem with us, please tell us.' => 'Se você acha que isso é um problema conosco, por favor, nos avise.',
    'Index' => 'Índice',
    'Name' => 'Nome',
    'Note that if you turn on the Yii debugger, you should be able to view the mail message on the mail panel of the debugger.' => 'Observe que se você ativar o depurador Yii, deverá ser capaz de ver a mensagem de email no painel de email do depurador.',
    'Oops! Looks like you followed a bad link.' => 'Ops! Parece que você seguiu um link errado.',
    'Please configure the <code>useFileTransport </code>property of the <code>mail </code>application component to be false to enable email sending.' => 'Por favor, configure a propriedade <code>useFileTransport</code> do componente de aplicação <code>mail</code> para falso para habilitar o envio de emails.',
    'Please fill out the following form to contact us.' => 'Por favor, preencha o seguinte formulário para entrar em contato conosco.',
    'Portuguese' => 'Português',
    'Russian' => 'Russo',
    'Spanish' => 'Espanhol',
    'Subject' => 'Assunto',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Obrigado por entrar em contato conosco. Vamos responder o mais rápido possível.',
    'This is the About page. You may modify the following file to customize its content.' => 'Esta é a página Sobre. Você pode modificar o arquivo a seguir para personalizar seu conteúdo.',
    'Username' => 'Nome de usuário',
    'Web Application' => 'Aplicação Web',
];
