<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О нас',
    'Because the application is in development mode, the email is not sent but saved as a file under.' => 'Поскольку приложение находится в режиме разработки, электронное письмо не отправляется, а сохраняется как файл под именем.',
    'Body' => 'Сообщение',
    'Captcha Code' => 'Код Captcha',
    'Chinese' => 'Китайский',
    'Contact' => 'Контакт',
    'Contact us' => 'Свяжитесь с нами',
    'Email' => 'Электронная почта',
    'English' => 'Английский',
    'Enter Body Here' => 'Введите текст сообщения здесь',
    'Enter Captcha Code Here' => 'Введите код Captcha здесь',
    'Enter Email Here' => 'Введите адрес электронной почты здесь',
    'Enter Subject Here' => 'Введите тему здесь',
    'Enter Username Here' => 'Введите имя пользователя здесь',
    'French' => 'Французский',
    'German' => 'Немецкий',
    'If you think this is a problem with us, please tell us.' => 'Если вы считаете, что это проблема с нами, пожалуйста, сообщите нам.',
    'Index' => 'Главная',
    'Name' => 'Имя',
    'Note that if you turn on the Yii debugger, you should be able to view the mail message on the mail panel of the debugger.' => 'Обратите внимание, что если вы включите отладчик Yii, вы сможете просматривать почтовое сообщение на панели почты отладчика.',
    'Oops! Looks like you followed a bad link.' => 'Упс! Похоже, вы перешли по неверной ссылке.',
    'Please configure the <code>useFileTransport </code>property of the <code>mail </code>application component to be false to enable email sending.' => 'Пожалуйста, настройте свойство <code>useFileTransport</code> компонента приложения <code>mail</code> на значение false, чтобы включить отправку электронной почты.',
    'Please fill out the following form to contact us.' => 'Пожалуйста, заполните следующую форму, чтобы связаться с нами.',
    'Portuguese' => 'Португальский',
    'Russian' => 'Русский',
    'Spanish' => 'Испанский',
    'Subject' => 'Тема',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо, что связались с нами. Мы ответим вам как можно скорее.',
    'This is the About page. You may modify the following file to customize its content.' => 'Это страница "О нас". Вы можете изменить следующий файл, чтобы настроить ее содержание.',
    'Username' => 'Имя пользователя',
    'Web Application' => 'Веб-приложение',
];
