<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'À propos',
    'Because the application is in development mode, the email is not sent but saved as a file under.' => 'Parce que l\'application est en mode de développement, l\'e-mail n\'est pas envoyé mais est enregistré en tant que fichier sous.',
    'Body' => 'Corps',
    'Captcha Code' => 'Code Captcha',
    'Chinese' => 'Chinois',
    'Contact' => 'Contact',
    'Contact us' => 'Contactez-nous',
    'Email' => 'E-mail',
    'English' => 'Anglais',
    'Enter Body Here' => 'Entrez le corps ici',
    'Enter Captcha Code Here' => 'Entrez le code Captcha ici',
    'Enter Email Here' => 'Entrez l\'e-mail ici',
    'Enter Subject Here' => 'Entrez le sujet ici',
    'Enter Username Here' => 'Entrez le nom d\'utilisateur ici',
    'French' => 'Français',
    'German' => 'Allemand',
    'If you think this is a problem with us, please tell us.' => 'Si vous pensez que c\'est un problème avec nous, veuillez nous le dire.',
    'Index' => 'Index',
    'Name' => 'Nom',
    'Note that if you turn on the Yii debugger, you should be able to view the mail message on the mail panel of the debugger.' => 'Notez que si vous activez le débogueur Yii, vous devriez pouvoir voir le message de courrier dans le panneau de courrier du débogueur.',
    'Oops! Looks like you followed a bad link.' => 'Oups ! On dirait que vous avez suivi un mauvais lien.',
    'Please configure the <code>useFileTransport </code>property of the <code>mail </code>application component to be false to enable email sending.' => 'Veuillez configurer la propriété <code>useFileTransport</code> du composant d\'application <code>mail</code> en faux pour activer l\'envoi d\'e-mails.',
    'Please fill out the following form to contact us.' => 'Veuillez remplir le formulaire suivant pour nous contacter.',
    'Portuguese' => 'Portugais',
    'Russian' => 'Russe',
    'Spanish' => 'Espagnol',
    'Subject' => 'Sujet',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Merci de nous avoir contactés. Nous vous répondrons dès que possible.',
    'This is the About page. You may modify the following file to customize its content.' => 'Il s\'agit de la page À propos. Vous pouvez modifier le fichier suivant pour personnaliser son contenu.',
    'Username' => 'Nom d\'utilisateur',
    'Web Application' => 'Application Web',
];
