
services:
  yii2-nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
    image: yii2-nginx:84
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8081:80'
    environment:
      TZ: "UTC"
