services:
  yii2-frankenphp:
    build:
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USER_NAME: ${USER_NAME:-www-data}
        GROUP_NAME: ${GROUP_NAME:-www-data}
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    container_name: yii2-frankenphp
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    env_file:
      - .env
    environment:
      TZ: "UTC"
      YII_DEBUG: "${YII_DEBUG:-false}"
      YII_ENV: "${YII_ENV:-prod}"
    ports:
      - '8081:80'
      - '8444:443'
      - '8444:443/udp'
    restart: always
    volumes:
      - ./:/app
      - caddy_config:/config
      - caddy_data:/data
      - composer_cache:/var/www/.composer/cache
    working_dir: /app
    tty: true

volumes:
  caddy_data:
  caddy_config:
  composer_cache:
