services:
  yii2-frankenphp:
    build:
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USER_NAME: ${USER_NAME:-www-data}
        GROUP_NAME: ${GROUP_NAME:-www-data}
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    container_name: yii2-frankenphp
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    env_file:
      - .env
    environment:
      TZ: "UTC"
      YII_DEBUG: "${YII_DEBUG:-false}"
      YII_ENV: "${YII_ENV:-prod}"
    ports:
      - '8081:80'
      - '8444:443'
      - '8444:443/udp'
    restart: always
    sysctls:
      - net.core.rmem_max=${UDP_BUFFER_SIZE:-7168000}
      - net.core.rmem_default=${UDP_BUFFER_SIZE:-7168000}
    volumes:
      - ./:/app
      - ${HOME}/.composer-docker/cache:/var/www/.composer/cache:delegated
      - caddy_data:/data
      - caddy_config:/config
    working_dir: /app
    tty: true

volumes:
  caddy_data:
  caddy_config:
