services:
  yii2-nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
    container_name: yii2-nginx
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    ports:
      - '8082:80'
      - '8445:443'
    environment:
      TZ: "UTC"
