#!/usr/bin/env php
<?php

declare(strict_types=1);

use yii\console\Application;
use Yiisoft\Config\Config;
use Yiisoft\Config\ConfigPaths;
use Yiisoft\Config\Modifier\RecursiveMerge;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = new Config(
    new ConfigPaths(__DIR__, 'config', 'vendor'),
    modifiers: [RecursiveMerge::groups('console', 'params', 'params-console')],
    paramsGroup: 'params-console',
);

$container = Yii::$container->setSingleton(Application::class, $config->get('comsole'));
$app = Yii::$container->get(Application::class);
$exitCode = $application->run();

exit($exitCode);
