<?php

declare(strict_types=1);

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Because the application is in development mode, the email is not sent but saved as a file under.' => '',
    'Body' => '',
    'Captcha Code' => '',
    'Contact' => '',
    'Contact us' => '',
    'Email' => '',
    'Enter Body Here' => '',
    'Enter Captcha Code Here' => '',
    'Enter Email Here' => '',
    'Enter Subject Here' => '',
    'Enter Username Here' => '',
    'If you think this is a problem with us, please tell us.' => '',
    'Index' => '',
    'Name' => '',
    'Note that if you turn on the Yii debugger, you should be able to view the mail message on the mail panel of the debugger.' => '',
    'Oops! Looks like you followed a bad link.' => '',
    'Please configure the <code>useFileTransport </code>property of the <code>mail </code>application component to be false to enable email sending.' => '',
    'Please fill out the following form to contact us.' => '',
    'Subject' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'This is the About page. You may modify the following file to customize its content.' => '',
    'Web Application' => '',
    'Yii v.2.2' => '',
    'site.selector.language.de' => 'German',
    'site.selector.language.en' => 'English',
    'site.selector.language.es' => 'Spanish',
    'site.selector.language.fr' => 'French',
    'site.selector.language.pt' => 'Portuguese',
    'site.selector.language.ru' => 'Russian',
    'site.selector.language.zh' => 'Chinese',
];
