<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Über uns',
    'Because the application is in development mode, the email is not sent but saved as a file under.' => 'Da die Anwendung im Entwicklungsmodus ist, wird die E-Mail nicht gesendet, sondern als Datei gespeichert unter.',
    'Body' => 'Nachrichtentext',
    'Captcha Code' => 'Captcha-Code',
    'Chinese' => 'Chinesisch',
    'Contact' => 'Kontakt',
    'Contact us' => 'Kontaktiere uns',
    'Email' => 'E-Mail',
    'English' => 'Englisch',
    'Enter Body Here' => 'Hier Nachricht eingeben',
    'Enter Captcha Code Here' => 'Hier Captcha-Code eingeben',
    'Enter Email Here' => 'Hier E-Mail eingeben',
    'Enter Subject Here' => 'Hier Betreff eingeben',
    'Enter Username Here' => 'Hier Benutzername eingeben',
    'French' => 'Französisch',
    'German' => 'Deutsch',
    'If you think this is a problem with us, please tell us.' => 'Wenn Sie denken, dass dies ein Problem bei uns ist, informieren Sie uns bitte.',
    'Index' => 'Startseite',
    'Name' => 'Name',
    'Note that if you turn on the Yii debugger, you should be able to view the mail message on the mail panel of the debugger.' => 'Beachten Sie, dass Sie, wenn Sie den Yii-Debugger aktivieren, die E-Mail-Nachricht im E-Mail-Panel des Debuggers anzeigen können.',
    'Oops! Looks like you followed a bad link.' => 'Hoppla! Sie sind einem fehlerhaften Link gefolgt.',
    'Please configure the <code>useFileTransport </code>property of the <code>mail </code>application component to be false to enable email sending.' => 'Bitte konfigurieren Sie die Eigenschaft <code>useFileTransport</code> des <code>mail</code>-Anwendungsbausteins als falsch, um das Versenden von E-Mails zu ermöglichen.',
    'Please fill out the following form to contact us.' => 'Bitte füllen Sie das folgende Formular aus, um uns zu kontaktieren.',
    'Portuguese' => 'Portugiesisch',
    'Russian' => 'Russisch',
    'Spanish' => 'Spanisch',
    'Subject' => 'Betreff',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Vielen Dank für Ihre Kontaktaufnahme. Wir werden uns so schnell wie möglich bei Ihnen melden.',
    'This is the About page. You may modify the following file to customize its content.' => 'Dies ist die Über-uns-Seite. Sie können die folgende Datei bearbeiten, um ihren Inhalt anzupassen.',
    'Username' => 'Benutzername',
    'Web Application' => 'Webanwendung',
];
