---
ignored:
  - DL3008 # Pin versions in apk add.
  - DL3015 # Avoid additional packages by specifying `--no-install-recommends`.
  - DL3022 # `COPY --from` should reference a previously defined `FROM` alias
  - DL4006 # Set the SHELL option -o pipefail before RUN with a pipe in it.
