---
paths:
  .github/workflows/**/*.yml:
    ignore:
      - '"pull_request" section is alias node but mapping node is expected'
      - '"push" section is alias node but mapping node is expected'
      - "section is alias node but mapping node is expected"
