<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Acerca de',
    'Because the application is in development mode, the email is not sent but saved as a file under.' => 'Debido a que la aplicación está en modo de desarrollo, el correo electrónico no se envía, pero se guarda como un archivo en.',
    'Body' => 'Cuerpo',
    'Captcha Code' => 'Código Captcha',
    'Contact' => 'Contacto',
    'Contact us' => 'Contáctanos',
    'Email' => 'Correo Electrónico',
    'English' => 'Inglés',
    'Enter Body Here' => 'Ingresa el Cuerpo Aquí',
    'Enter Captcha Code Here' => 'Ingresa el Código Captcha Aquí',
    'Enter Email Here' => 'Ingresa el Correo Electrónico Aquí',
    'Enter Subject Here' => 'Ingresa el Asunto Aquí',
    'Enter Username Here' => 'Ingresa el Nombre de Usuario Aquí',
    'French' => 'Francés',
    'If you think this is a problem with us, please tell us.' => 'Si crees que esto es un problema con nosotros, por favor cuéntanos.',
    'Index' => 'Índice',
    'Name' => 'Nombre',
    'Note that if you turn on the Yii debugger, you should be able to view the mail message on the mail panel of the debugger.' => 'Ten en cuenta que si habilitas el depurador de Yii, deberías poder ver el mensaje de correo en el panel de correo del depurador.',
    'Oops! Looks like you followed a bad link.' => '¡Ups! Parece que has seguido un enlace incorrecto.',
    'Please configure the <code>useFileTransport </code>property of the <code>mail </code>application component to be false to enable email sending.' => '',
    'Please configure the <code>useFileTransport</code> property of the <code>mail</code> application component to be false to enable email sending.' => '@@Por favor configura la propiedad <code>useFileTransport</code> del componente de aplicación <code>mail</code> en falso para habilitar el envío de correos electrónicos.@@',
    'Please fill out the following form to contact us.' => 'Por favor completa el siguiente formulario para contactarnos.',
    'Portuguese' => 'Portugués',
    'Russian' => 'Ruso',
    'Spanish' => 'Español',
    'Subject' => 'Asunto',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Gracias por contactarnos. Te responderemos lo antes posible.',
    'This is the About page. You may modify the following file to customize its content.' => 'Esta es la página de Acerca de. Puedes modificar el siguiente archivo para personalizar su contenido.',
    'Username' => 'Nombre de Usuario',
    'Web Application' => 'Aplicación web',
];
