on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: dependency-check

jobs:
  composer-require-checker:
    uses: php-forge/actions/.github/workflows/composer-require-checker.yml@main
    secrets:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
