name: Docker CI

on:
  pull_request:
    paths:
      - 'docker/**'
      - 'docker-compose*.yml'
      - '.github/workflows/docker.yml'
  push:
    paths:
      - 'docker/**'
      - 'docker-compose*.yml'
      - '.github/workflows/docker.yml'

jobs:
  test-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Build and start Containers.
        run: docker-compose build --no-cache && docker-compose up -d

      - name: Update Vendor Packages.
        run: docker exec yii2-apache composer update --prefer-dist -vvv

      - name: Run Codeception Tests
        run: docker exec yii2-apache vendor/bin/codecept run

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Build and start Containers.
        run: docker-compose -f docker-compose-nginx.yml build --no-cache && docker-compose -f docker-compose-nginx.yml up -d

      - name: Update Vendor Packages.
        run: docker exec yii2-nginx composer update --prefer-dist -vvv

      - name: Run Codeception Tests
        run: docker exec yii2-nginx vendor/bin/codecept run
