name: Docker CI

on:
  pull_request:
    paths:
      - 'docker/**'
      - 'docker-compose*.yml'
      - '.github/workflows/docker.yml'
  push:
    paths:
      - 'docker/**'
      - 'docker-compose*.yml'
      - '.github/workflows/docker.yml'

jobs:
  test-apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install docker compose.
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start containers.
        run: docker-compose up -d --build

      - name: Wait for container to be ready.
        run: |
          echo "Waiting 30 seconds for container initialization..."
          sleep 30
          docker logs yii2-apache

      - name: Codeceptcion build.
        run: docker exec yii2-apache vendor/bin/codecept build

      - name: Run codeception tests.
        run: docker exec yii2-apache vendor/bin/codecept run

  test-frankenphp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install docker compose.
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start containers.
        run: docker-compose -f docker-compose.frankenphp.yml up -d --build

      - name: Wait for container to be ready.
        run: |
          echo "Waiting 30 seconds for container initialization..."
          sleep 30
          docker logs yii2-frankenphp

      - name: Codeception build.
        run: docker exec yii2-frankenphp vendor/bin/codecept build

      - name: Run codeception build and tests.
        run: docker exec yii2-frankenphp vendor/bin/codecept run

  test-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install docker Compose.
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start containers.
        run: docker-compose -f docker-compose.nginx.yml up -d --build

      - name: Wait for container to be ready.
        run: |
          echo "Waiting 30 seconds for container initialization..."
          sleep 30
          docker logs yii2-nginx

      - name: Codeception build.
        run: docker exec yii2-nginx vendor/bin/codecept build

      - name: Run codeception build and tests.
        run: docker exec yii2-nginx vendor/bin/codecept run
